# Publish all joint states -----------------------
joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50
    
# Joint Trajectory Controller -----------------------
niryo_one_follow_joint_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints: 
        - joint_1  
        - joint_2
        - joint_3  
        - joint_4  
        - joint_5  
        - joint_6
    constraints:
        goal_time: 1.0 
        joint_1: {trajectory: 0.1, goal: 0.1}
        joint_2: {trajectory: 0.1, goal: 0.1}
        joint_3: {trajectory: 0.1, goal: 0.1}
        joint_4: {trajectory: 0.1, goal: 0.1}
        joint_5: {trajectory: 0.1, goal: 0.1}
        joint_6: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 1.0
    gains:
      joint_1: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      joint_2: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      joint_3: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      joint_4: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      joint_5: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
      joint_6: {p: 100,  d: 0.1, i: 0, i_clamp: 0}
