#
#
# Validation for a RobotMoveCommand
# (taken from urdf)
# 

joint_limits:
    j1:
        min: -3.05433
        max: 3.05433
    j2:
        min: -1.91986
        max: 0.640187
    j3:
        min: -1.397485
        max: 1.570796
    j4:
        min: -3.05433
        max: 3.05433
    j5:
        min: -1.74533
        max: 1.91986
    j6:
        min: -2.57436
        max: 2.57436

position_limits:
    x:
        min: -0.50
        max: 0.50
    y:
        min: -0.50
        max: 0.50
    z:
        min: -0.15
        max: 0.65

rpy_limits:
    roll:
        min: -3.14159
        max: 3.14159
    pitch:
        min: -3.14159
        max: 3.14159
    yaw:
        min: -3.14159
        max: 3.14159

tool_limits:
    gripper_open_speed:
        min: 0
        max: 1023
    gripper_close_speed:
        min: 0
        max: 1023
