controller_list:
  - name: fake_niryo_one_gripper_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_only_controller
    joints:
      - joint_base_to_mors_1
      - joint_base_to_mors_2