#
#  Stepper caracteristics for hardware V1
#

stepper_1_gear_ratio: 6.0625
stepper_2_gear_ratio: 8.3125
stepper_3_gear_ratio: 7.875
stepper_4_gear_ratio: 5.0

stepper_1_offset_position: 3.05433
stepper_2_offset_position: 0.628319
stepper_3_offset_position: -1.401
stepper_4_offset_position: 2.791

stepper_1_home_position: 0.0
stepper_2_home_position: 0.628319
stepper_3_home_position: -1.401
stepper_4_home_position: 0.0

stepper_1_direction: -1.0
stepper_2_direction: -1.0
stepper_3_direction: 1.0
stepper_4_direction: -1.0

stepper_1_max_effort: 90
stepper_2_max_effort: 140
stepper_3_max_effort: 140
stepper_4_max_effort: 90
